In [4]:
from typing import List
import math

values = [[-1,0, 10.5], [float('nan'), float('inf'), -float('inf')]]
print(values)

def sanitize_json_numbers(values: List[List[float]]):
    def replace_value(value: float):
        if math.isnan(value):
            return 'NaN'
        elif math.isinf(value) and value > 0:
            return 'Inf'
        elif math.isinf(value) and value < 0:
            return '-Inf'
        else: 
            return value
    return [[replace_value(i) for i in l] for l in values]

print(sanitize_json_numbers(values))
# s = [[i for i in l] for l in values]

# print(s)

[[-1, 0, 10.5], [nan, inf, -inf]]
[[-1, 0, 10.5], ['NaN', 'Inf', '-Inf']]


In [3]:
import torch
def pt(n,t):
    print(n)
    print(t.size())
    print(t)
    print()
    
a = torch.Tensor([
    [
        [1,1,4,4],
        [1,1,4,4],
    ],
    [
        [2,2,5,5],
        [2,2,5,5],
    ],
    [
        [3,3,6,6],
        [3,3,6,6],
    ],
])

a = torch.Tensor([
    [
        [1,2,3],
        [1,2,3],
        [4,5,6],
        [4,5,6],
    ],
    [
        [1,2,3],
        [1,2,3],
        [4,5,6],
        [4,5,6],
    ],
])

pt('orig', a)
pt('permute', a.permute(0,2,1))
pt('transpose1', a.transpose(-1,-2).transpose(-2,-3))


orig
torch.Size([2, 4, 3])
tensor([[[1., 2., 3.],
         [1., 2., 3.],
         [4., 5., 6.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [1., 2., 3.],
         [4., 5., 6.],
         [4., 5., 6.]]])

permute
torch.Size([2, 3, 4])
tensor([[[1., 1., 4., 4.],
         [2., 2., 5., 5.],
         [3., 3., 6., 6.]],

        [[1., 1., 4., 4.],
         [2., 2., 5., 5.],
         [3., 3., 6., 6.]]])

transpose1
torch.Size([3, 2, 4])
tensor([[[1., 1., 4., 4.],
         [1., 1., 4., 4.]],

        [[2., 2., 5., 5.],
         [2., 2., 5., 5.]],

        [[3., 3., 6., 6.],
         [3., 3., 6., 6.]]])



In [1]:
import torch
def pt(n,t):
    print(n)
    print(t.size())
    print(t)
    print()
    
a = torch.tensor([[1,2,3],[10,20,30]]).float()
b = torch.zeros(2,3)
i1 = torch.tensor([[2,1,0], [2,0,1]], dtype=torch.long)
i0 = torch.tensor([[0,1,0], [1,0,1]], dtype=torch.long)

pt('a', a)
pt('b', b)
s1 = torch.zeros(2,3).scatter_(1, i1, a)
pt('s1', s1)
s0 = torch.zeros(2,3).scatter_(0, i0, a)
pt('s0', s0)

g1 = a.gather(1, i1)
pt('g1', g1)
g0 = a.gather(0, i0)
pt('g0', g0)

g = a.gather(0, torch.tensor([[0,0,1], [0,0,1], [1,0,1]], dtype=torch.long))
pt('g_0', g)

g = a.gather(1, torch.tensor([[0,1, 1], [0,0, 0]], dtype=torch.long))
pt('g_1', g)



a
torch.Size([2, 3])
tensor([[ 1.,  2.,  3.],
        [10., 20., 30.]])

b
torch.Size([2, 3])
tensor([[0., 0., 0.],
        [0., 0., 0.]])

s1
torch.Size([2, 3])
tensor([[ 3.,  2.,  1.],
        [20., 30., 10.]])

s0
torch.Size([2, 3])
tensor([[ 1., 20.,  3.],
        [10.,  2., 30.]])

g1
torch.Size([2, 3])
tensor([[ 3.,  2.,  1.],
        [30., 10., 20.]])

g0
torch.Size([2, 3])
tensor([[ 1., 20.,  3.],
        [10.,  2., 30.]])

g_0
torch.Size([3, 3])
tensor([[ 1.,  2., 30.],
        [ 1.,  2., 30.],
        [10.,  2., 30.]])

g_1
torch.Size([2, 3])
tensor([[ 1.,  2.,  2.],
        [10., 10., 10.]])



In [6]:
a = [torch.arange(x,x + 4).view(2,2) for x in range(1, 3*4 + 1, 4)
]
# for i,t in enumerate(a):
#     pt(f'a[{i}]', t)
    
data = torch.stack(a)
pt('data', data)

r = data.clone()
r.unsqueeze_(dim=0)
pt('r', r)
pt('', r[0, 0])


index = torch.full((2,2), 0, dtype=torch.long).unsqueeze(dim=0)
# pt('g', data.gather(0, torch.tensor([[[1, 1], [1, 1]]])))
# pt('g_', data.gather(0, index))
reorder = data.index_select(0, torch.tensor([2, 1, 0, 0]))
pt('i', reorder)
pt('v', reorder.view((2,2,2,2)))

data
torch.Size([3, 2, 2])
tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])

r
torch.Size([1, 3, 2, 2])
tensor([[[[ 1,  2],
          [ 3,  4]],

         [[ 5,  6],
          [ 7,  8]],

         [[ 9, 10],
          [11, 12]]]])


torch.Size([2, 2])
tensor([[1, 2],
        [3, 4]])

i
torch.Size([4, 2, 2])
tensor([[[ 9, 10],
         [11, 12]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 1,  2],
         [ 3,  4]],

        [[ 1,  2],
         [ 3,  4]]])

v
torch.Size([2, 2, 2, 2])
tensor([[[[ 9, 10],
          [11, 12]],

         [[ 5,  6],
          [ 7,  8]]],


        [[[ 1,  2],
          [ 3,  4]],

         [[ 1,  2],
          [ 3,  4]]]])



In [26]:


a = torch.arange(0, 10)
pt('a', a)
pt('e', a.expand(4,10).contiguous().view(-1, 40))

pt('e2', a.expand(4,10).transpose(0,1).contiguous().view(-1, 40))


a
torch.Size([10])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

e
torch.Size([1, 40])
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3,
         4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

e2
torch.Size([1, 40])
tensor([[0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5,
         6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 9]])



In [22]:
a = torch.arange(1, 25)
pt('a', a)
e = a.view(-1, 2, 3)
pt('e', e)

a
torch.Size([24])
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])

e
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])



In [31]:
image_rows = 8
items_per_row = 2
expand_width = int(image_rows/items_per_row)

indices = torch.arange(0, items_per_row).expand(expand_width, items_per_row).contiguous().view(-1, image_rows)
indices_offset = torch.arange(0, items_per_row).expand(expand_width, items_per_row).transpose(0,1).contiguous().view(-1, image_rows)
i = indices.add(indices_offset)

pt('a', indices)
pt('o', indices_offset)
pt('i', i)

a
torch.Size([1, 8])
tensor([[0, 1, 0, 1, 0, 1, 0, 1]])

o
torch.Size([1, 8])
tensor([[0, 0, 0, 0, 1, 1, 1, 1]])

i
torch.Size([1, 8])
tensor([[0, 1, 0, 1, 1, 2, 1, 2]])



In [45]:
a = torch.arange(1,25)
w = 2
h = 3
a = a.view(-1,w*h)
pt('a', a)


i = torch.arange(0, w*h)
i = i.view(w, h).transpose(0,1).contiguous().view(-1)
pt('i', i)

ri = a.index_select(1, i).view(-1)
pt('ri', ri)

a
torch.Size([4, 6])
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]])

i
torch.Size([6])
tensor([0, 3, 1, 4, 2, 5])

ri
torch.Size([24])
tensor([ 1,  4,  2,  5,  3,  6,  7, 10,  8, 11,  9, 12, 13, 16, 14, 17, 15, 18,
        19, 22, 20, 23, 21, 24])



In [50]:
torch.tensor([[1,2], [3,4]]).expand([3,2,-1])

tensor([[[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]]])

In [11]:
s = torch.tensor([
            [0, 1, 0],  # 5
            [0, 1, 2],  # 2
            [0, 1, 3],  # 1
            [0, 1, 0],  # 1
        ])
mask = s == 2
pt('mask', mask)
mask.any(dim=1)
s[2,:]

mask
torch.Size([4, 3])
tensor([[0, 0, 0],
        [0, 0, 1],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.uint8)



tensor([0, 1, 3])